# Generated by Django 5.0 on 2024-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal_app', '0005_alter_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
