# Generated by Django 5.0 on 2024-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal_app', '0006_category_name_en_us_category_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='NE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='NE', max_length=255, null=True),
        ),
    ]
