# Generated by Django 5.0 on 2024-03-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal_app', '0007_post_type_en_us_post_type_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_ru',
        ),
    ]
