# Generated by Django 5.0 on 2024-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal_app', '0008_remove_post_type_en_us_remove_post_type_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
